[package]
name = "trophies"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = {version = "1.47.1", features = ["full"]}
