
This is my discord bot for getting achievements with my friends :D 

* Steps of the Project
1. The internal logic needs to be sound - all commands working, all unit tests passed, using internal data only.
2. Then, I need to hook it into Discord's API.

I will do this by creating local implementations of the Discord API bits I'll have to access -
e.g. display names, avatars, user IDs, etc. - as traits I can then apply to both local structs,
and structs from Poise.

** Local Implementation
First, I need to find all of the Discord API objects I'll need, and implement them locally.
*Despite asynchronicity not being required for the local implementation, all functions /must/ be async.*

*** Sending Messages
**** CustomSend Macro
This will be a macro that accepts several parts.
The macro will expand to the definition of a struct, which will then have a method on it run.
The method will send a message, using ~ctx~.

- ~title~ - the title of the embed / message
- ~description~ - the description of the embed / message
- ~message~ - the raw contents of the message
- ~ephemeral~ - whether the message is only visible to its sender
- ~include_author~ - whether to include the display name and avatar of the sender

**** SendMessage Trait
Has one main method, to send a message.
The implementation for ~serenity::Context~ will be complex, constructing things using every part of ~CustomSend~. Meanwhile, the implementation locally will simply format it all into a string, and send it using ~println!~.

*** Context
Serenity comes with a handy Context type, that contains all of the information about the message.
A version of this must be implemented locally.

This will contain a few things - a generic User ID and an implementation of the ~SendMessage~ trait, and anything else I think of later (non-exhaustive struct).

It will be initialised at the start of tests, and passed to every unit test.

* Todo List
** TODO CustomSend Macro
** TODO Local Context Struct
** TODO [2/3] SendMessage Trait
*** DONE Basic SendMessage Implementation
*** DONE SendMessage implementation for Local Context
*** TODO SendMessage implementation for Discord
** TODO Player struct
** TODO Saved Data Storage
